# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: dice-roll-js Integration Action

on:
  release:
    types: [ created ]

env:
  NODE_VERSION: 12.x

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run Standard
      run: standard
    - name: Run Jest
      run: npm run jest
    - name: Run Build
      run: npm run webpack
    - name: List output files
      run: ls
